### ISSUE TITLE
Convert different format .xml and .json

### ISSUE THREAD

**Issue by andikira** [Cartucho/mAP#3]
Hallo @Cartucho, i am newbie in computer programming i got frustrated to search how to calculate mAP, i think this is good repo for that.
But i have some problem, i use darkflow to train my own data. The result of test data prediction is .json file format like this (to fill in predicted folder)
 
[{"label": "RBC", "confidence": 0.98, "topleft": {"x": 252, "y": 0}, "bottomright": {"x": 373, "y": 81}} . . . ]

and annotation in .xml like this (to fill in ground-truth folder)
![image](https://user-images.githubusercontent.com/37479922/38103411-7ac3821c-33b0-11e8-93ba-05e7a7933020.png)

i think information for ground-truth and predicted is enough for run in your repo but this form in different format. Do you have any suggestion how to convert both of that to match in your repo ? 

thanks in advance and sorry for my bad English

**Comment by Cartucho** [comment]
Hey @andikira , welcome!

Good call I have an `extra` folder where I will be covering cases like this one, for example currently, I already have a code to convert yolo to this format.

I did not cover the darkflow case yet but would be glad to add it. Is there a way you could send me some of the files so I can test it? to.cartucho@gmail.com

**Comment by Cartucho** [comment]
Done! You can find the instructions in the `extra/` folder.
Basically, you just have to run two python scripts.

**Comment by andikira** [comment]
wow sir, i can't be happier, this repo works perfectly, very great. 
I think calculating mAP on darkflow is still an issue, they have to see this repo. 
Thank you so much sir
